vk_project/posting/urls.py
from django.urls import path

from .views import GroupView, IndexView, UserView, UsersView, ActivateView

app_name = 'posting'
urlpatterns = [
    path('', IndexView.as_view(), name='posting'),
    path('group/<int:pk>/', GroupView.as_view(), name='groups'),
    path('users/', UsersView.as_view(), name='users'),
    path('users/<int:pk>', UserView.as_view(), name='user'),
    path('users/activate/<int:pk>', ActivateView.as_view(), name='activate')
]

vk_project/vk_scraping_posting/urls.py
from django.contrib import admin
from django.urls import path, include

from posting.views import GroupView

urlpatterns = [
    path('moderation/', include('moderation.urls')),
    path('admin/', admin.site.urls),
    path('', include('shapranov.urls')),
    path('posting/', include('posting.urls')),
]

admin.site.index_template = 'admin/custom_index.html'

vk_project/posting/models/auth_code.py
from django.db import models


class AuthCode(models.Model):
    code = models.CharField(max_length=8, null=False, default='', blank=True)
    user = models.ForeignKey('posting.User', on_delete=models.CASCADE)
    create_dt = models.DateTimeField(auto_now_add=True)
    used = models.BooleanField(default=False)

vk_project/posting/models/block.py
from django.db import models
from datetime import timedelta
from django.utils import timezone


class Block(models.Model):
    AD = 'ad'
    LACK_OF_RECORDS = 'lack of records'
    RATE_LIMIT = 'rate limit'
    RECENT_POSTS = 'recent posts'
    POSTING = 'posting'

    REASONS = (
        (AD, 'ad'),
        (LACK_OF_RECORDS, 'lack of records'),
        (RATE_LIMIT, 'rate limit'),
        (RECENT_POSTS, 'recent posts'),
        (POSTING, 'posting'),
    )

    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    active_before = models.DateTimeField(null=True, blank=False)
    reason = models.CharField(null=True, choices=REASONS, max_length=64, blank=False)
    group = models.ForeignKey('posting.Group', on_delete=models.CASCADE, null=True, related_name='blocks', blank=False)

    def activate(self, group, reason, period_in_minutes):
        fields = ['reason', 'active_before', 'is_active', 'group']
        now = timezone.now()

        self.active_before = now + timedelta(minutes=period_in_minutes)
        self.active_before.replace(second=0, microsecond=0)

        self.reason = reason
        self.group = group
        self.is_active = True

        self.save(update_fields=fields)

    def deactivate(self):
        fields = ['is_active']

        self.is_active = False

        self.save(update_fields=fields)

    def is_block_active(self):
        if self.is_active and timezone.now() >= self.active_before:
            self.deactivate()
        return self.is_active

    def __str__(self):
        return \
            f'Block {self.id} {self.is_active is True} for group {self.group} ' \
            f'before {self.active_before}, {self.reason}'

    def __repr__(self):
        return \
            f'Block {self.id} {self.is_active is True} for group {self.group} ' \
            f'before {self.active_before}, {self.reason}'

    class Meta:
        verbose_name = 'Блокировка'
        verbose_name_plural = 'Блокировки'

vk_project/posting/models/group.py
import datetime

from django.contrib.postgres.fields import ArrayField
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils import timezone

from posting.models.block import Block
from posting.models.user import User
from scraping.models import Attachment, Record, ScrapingHistory


class Group(models.Model):
    COMMON = 'common'
    MOVIE_COMMON = 'movie common'
    MOVIE_SPECIAL = 'movie special'
    MUSIC_COMMON = 'music common'
    HOROSCOPES_COMMON = 'horoscopes common'
    HOROSCOPES_MAIN = 'horoscopes main'

    GROUP_TYPE_CHOICES = (
        (COMMON, 'Обычная'),
        (MOVIE_COMMON, 'Обычные фильмы'),
        (MOVIE_SPECIAL, 'Сторонние фильмы'),
        (MUSIC_COMMON, 'Обычная музыка'),
        (HOROSCOPES_COMMON, 'Обычные гороскопы'),
        (HOROSCOPES_MAIN, 'Основные гороскопы')
    )

    domain_or_id = models.CharField(max_length=32, verbose_name='Domain/id группы цели', primary_key=True)
    url = models.URLField(max_length=128, verbose_name='Ссылка', blank=True, default='')
    group_type = models.CharField(choices=GROUP_TYPE_CHOICES, max_length=128, verbose_name='Тип группы', default=COMMON)
    statistic_url = models.URLField(max_length=256, verbose_name='Ссылка на статистику', blank=True, default='')
    name = models.CharField(max_length=128, verbose_name='Название', blank=True, default='')
    group_id = models.IntegerField(null=True, blank=False)
    is_posting_active = models.BooleanField(default=True, verbose_name='Постинг активен?')
    is_pin_enabled = models.BooleanField(default=True, verbose_name='Закреплять лучшие посты?')
    posting_time = models.TimeField(verbose_name='Время постинга', default=datetime.time(00, 00))
    user = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='groups', blank=True, null=True)
    callback_api_token = models.CharField(max_length=128, verbose_name='Ответ для callback api', blank=True, default='')
    donors = models.ManyToManyField('scraping.Donor', blank=True)

    is_text_delete_enabled = models.BooleanField(default=False, verbose_name='Убирать текст из постов?')
    is_text_filling_enabled = models.BooleanField(default=False, verbose_name='Переносить текст на изображение?')
    is_image_mirror_enabled = models.BooleanField(default=False, verbose_name='Отзеркаливать изображения без текста?')
    is_changing_image_to_square_enabled = models.BooleanField(default=False,
                                                              verbose_name='Приводить изображения к '
                                                                           'более квадратному виду?')
    RGB_image_tone = models.CharField(max_length=15, blank=True, default='',
                                      verbose_name='Применять RBG тон к изображениям (R G B factor)')
    is_photos_shuffle_enabled = models.BooleanField(default=False, verbose_name='Перемешивать фото?')
    is_audios_shuffle_enabled = models.BooleanField(default=False, verbose_name='Перемешивать аудиозаписи?')
    is_merge_images_enabled = models.BooleanField(default=False, verbose_name='Объединять 6 изображений в одно?')
    is_replace_russian_with_english = models.BooleanField(default=False,
                                                          verbose_name='Заменять русские буквы английскими?')
    is_copyright_needed = models.BooleanField(default=False, verbose_name='Указывать источик в записях')

    is_additional_text_enabled = models.BooleanField(default=False,
                                                     verbose_name='Добавлять к записи дополнительный текст?')
    last_used_additional_text_id = models.IntegerField(null=True, default=0)

    is_background_abstraction_enabled = models.BooleanField(default=False,
                                                            verbose_name='Переносить картинку в шаблон CD-диска?')
    last_used_background_abstraction_id = models.IntegerField(null=True, default=0)
    is_music_genre_epithet_enabled = models.BooleanField(default=False,
                                                         verbose_name='Добавлять эпитет перед музыкальным жанром?')
    last_used_music_genre_epithet_id = models.IntegerField(null=True, default=0)

    members_count = models.IntegerField(null=True, verbose_name='Участники')
    members_growth = models.IntegerField(null=True, verbose_name='Прирост')
    number_of_posts_yesterday = models.IntegerField(null=True, verbose_name='Посты за вчера')
    number_of_ad_posts_yesterday = models.IntegerField(null=True, verbose_name='Реклама за вчера')
    statistics_last_update_date = models.DateTimeField(null=True)

    male_weekly_average_count = models.IntegerField(default=0,
                                                    verbose_name='Среднее количество мужчин за неделю')
    female_weekly_average_count = models.IntegerField(default=0,
                                                      verbose_name='Среднее количество женщин за неделю')
    sex_last_update_date = models.DateTimeField(null=True)
    banned_origin_attachment_types = ArrayField(
        models.CharField(choices=Attachment.TYPE_CHOICES, blank=True, null=True, max_length=16),
        blank=True,
        null=True,
        verbose_name='Недопустимые вложения для записей',
        help_text=f'Типы вложений записей, которые не нужны в этой группе. '
                  f'Примеры:{[c[1] for c in Attachment.TYPE_CHOICES]}'
    )

    posting_interval = models.IntegerField(
        default=60,
        validators=[MaxValueValidator(1410), MinValueValidator(30)],
        verbose_name='Интервал постинга',
        help_text='Количество минут между постингом. Минимально - 30 минут. Максимально - 1410 (сутки).'
    )
    posting_minute_base = models.IntegerField(
        default=0,
        validators=[MaxValueValidator(59), MinValueValidator(0)],
        verbose_name='Минута отчета',
        help_text='С этой минуты будет начинаться отчёт постинга.'
    )
    # https://trello.com/c/ojA55xRF/272
    donors_alternation = models.BooleanField(
        default=True,
        verbose_name='Чередование доноров',
        help_text='Если настройка включена, 2 поста из одного донора подряд не будут выходить'
    )

    horoscope_postfix = models.TextField(
        max_length=256, default='', null=False, blank=True,
        verbose_name='Текст после обрезки основного текста гороскопа',
        help_text='Работает, если включена настройка '
    )

    def save(self, *args, **kwargs):
        if self.domain_or_id.isdigit():
            self.url = 'https://vk.com/club{}'.format(self.domain_or_id)
            self.statistic_url = 'https://vk.com/stats?gid={group_id_int}'.format(group_id_int=self.domain_or_id)
        else:
            self.url = 'https://vk.com/{}'.format(self.domain_or_id)
            if self.group_id:
                self.statistic_url = 'https://vk.com/stats?gid={group_id_int}'.format(group_id_int=self.group_id)

        super(Group, self).save(*args, **kwargs)

    def __str__(self):
        return self.__repr__()

    def __repr__(self):
        return f'Group {self.group_id} "{self.name}" {self.url}'

    def get_auditory_percents(self):
        sum_of_auditory = (self.male_weekly_average_count + self.female_weekly_average_count)

        if sum_of_auditory == 0:
            return 0.5, 0.5

        male_percent = self.male_weekly_average_count / sum_of_auditory
        female_percent = 1 - male_percent

        return male_percent, female_percent

    def return_posting_time_list(self, base_minute=None, interval=None):
        minutes = base_minute or self.posting_minute_base
        interval = interval or self.posting_interval
        result = []

        while minutes < 1440:
            hour = minutes // 60
            posting_minute = minutes % 60
            result.append((hour, posting_minute))
            minutes += interval

        return result

    def is_blocked(self):
        for block in self.blocks.all():
            if block.is_block_active():
                result = True
                break
        else:
            result = False

        return result

    def set_block(self, reason, period_in_minutes):
        new_block = Block.objects.create()
        new_block.activate(self, reason=reason, period_in_minutes=period_in_minutes)

        return new_block

    def get_next_posting_time(self) -> datetime.datetime:
        now = timezone.now()
        posting_time_intervals = self.return_posting_time_list()
        result = now

        for item in posting_time_intervals:
            item_time = now.replace(hour=item[0], minute=item[1], second=0, microsecond=0)
            result = item_time
            if item_time >= now:
                break

        return result

    def get_active_donors_number(self):
        return self.donors.filter(is_involved=True).count()

    def get_last_record(self):
        latest_record = common_record = self.records.order_by('-post_in_group_date').first()

        if self.horoscopes.exists():
            horoscope_record = self.horoscopes.filter(post_in_group_date__isnull=False) \
                .order_by('-post_in_group_date').first()

            if (
                    common_record
                    and horoscope_record
                    and horoscope_record.post_in_group_date
                    and horoscope_record.post_in_group_date > common_record.post_in_group_date
            ):
                latest_record = horoscope_record

        return latest_record

    def get_last_common_record(self):
        common_record = self.records.order_by('-post_in_group_date').first()
        return common_record

    def get_last_record_time(self):
        last_record = self.get_last_record()
        if last_record is not None and last_record.post_in_group_date is not None:
            delta = last_record.post_in_group_date
        else:
            delta = None
        return delta

    def get_ready_records(self):

vk_project/posting/models/misc.py
from django.db import models

from scraping.models import Record


class MusicGenreEpithet(models.Model):
    group = models.ForeignKey('posting.Group', on_delete=models.CASCADE, related_name='music_genre_epithets')
    text_for_male = models.TextField(max_length=256, default='',
                                     verbose_name='Эпитет для музыкального жанра мужского рода')
    text_for_female = models.TextField(max_length=256, default='',
                                       verbose_name='Эпитет для музыкального жанра женского рода')

    class Meta:
        verbose_name = 'Эпитет'
        verbose_name_plural = 'Эпитеты'


class AdditionalText(models.Model):
    group = models.ForeignKey('posting.Group', on_delete=models.CASCADE, related_name='additional_texts')
    text = models.TextField(max_length=1024, default='',
                            verbose_name='Дополнительный текст, единственное число')
    text_plural = models.TextField(max_length=1024, default='',
                                   verbose_name='Дополнительный текст, множественное число')

    class Meta:
        verbose_name = 'Текст'
        verbose_name_plural = 'Тексты'


class AdRecord(models.Model):
    ad_record_id = models.IntegerField()
    group = models.ForeignKey('posting.Group', on_delete=models.CASCADE, related_name='ad_records')
    post_in_group_date = models.DateTimeField()


class BackgroundAbstraction(models.Model):
    picture = models.ImageField(upload_to='backgrounds')

    def __str__(self):
        return f'{self.id}'

    class Meta:
        app_label = 'posting'


class PostingHistory(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    group = models.ForeignKey('posting.Group', on_delete=models.CASCADE, related_name='history')
    record = models.ForeignKey(Record, on_delete=models.CASCADE, related_name='history')

    candidates_number = models.IntegerField()
    candidates_internal_ids = models.CharField(max_length=2500)

    class Meta:
        verbose_name = 'История постинга'
        verbose_name_plural = 'История постинга'


class ServiceToken(models.Model):
    app_service_token = models.CharField(max_length=256, verbose_name='Сервисный ключ приложения', primary_key=True)
    last_used = models.DateTimeField(null=True)

    def __str__(self):
        return self.app_service_token

    class Meta:
        verbose_name = 'Сервисный токен'
        verbose_name_plural = 'Сервисные токены'

vk_project/tg_core/models/base.py
from django.db import models
from django.utils import timezone


class BaseModel(models.Model):
    # Fields
    created_dt = models.DateTimeField(editable=False)
    modified_dt = models.DateTimeField(editable=False)

    # Attributes
    objects = models.Manager()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.created_dt = timezone.now()
        self.modified_dt = timezone.now()
        return super().save(*args, **kwargs)

    class Meta:
        abstract = True

vk_project/posting/views.py
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import generic

from posting.models import Group, User, AuthCode
from services.vk.core import activate_two_factor


class IndexView(LoginRequiredMixin, generic.ListView):
    raise_exception = True
    template_name = 'posting/index.html'
    context_object_name = 'groups'

    def get_queryset(self):
        return Group.objects.all()


class GroupView(LoginRequiredMixin, generic.DetailView):
    raise_exception = True
    template_name = 'posting/group.html'

    model = Group


class UsersView(LoginRequiredMixin, generic.ListView):
    raise_exception = True
    template_name = 'posting/users.html'
    context_object_name = 'users'

    def get_queryset(self):
        return User.objects.all()


class UserView(LoginRequiredMixin, generic.DetailView):
    raise_exception = True
    template_name = 'posting/user.html'

    model = User

    def post(self, request, *args, **kwargs):
        print(request)
        print(dict(request.POST))

        result = AuthCode.objects.create(
            code=request.POST.get('code'),
            user_id=int(request.POST.get('user_pk'))
        )

        return JsonResponse(data={'result': result.pk})


class ActivateView(LoginRequiredMixin, generic.View):
    raise_exception = True

    def post(self, request, *args, **kwargs):
        user = User.objects.get(pk=int(request.POST.get('user_pk')))
        result = activate_two_factor(user)

        return JsonResponse(data={'result': result})

vk_project/posting/templates/posting/base.html
{% load bootstrap4 %}

{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <title>Title</title>
</head>
<body>
{% block navbar %}

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div>
            <div class="navbar-nav">
                <a class="nav-item nav-link" href={% url 'posting:posting' %}>Groups</a>
                <a class="nav-item nav-link" href={% url 'posting:users' %}>Admins</a>
            </div>
        </div>
    </nav>

{% endblock %}
{% block content %}{% endblock %}
</body>
</html>

vk_project/posting/templates/posting/group.html
{% extends 'posting/base.html' %}

{% load recrods_filter %}


{% block content %}
    <div class="container">
        <h1>{{ object.name }}
            <a href="{% url 'admin:posting_group_change' group.pk %}">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                     fill="currentColor"
                     class="bi bi-pen" viewBox="0 0 16 16">
                    <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"></path>
                </svg>
            </a>
        </h1>
    </div>

    <div class="container">
        <h3>Общая информация</h3>
        <p>Активных источников:<b> {{ object.get_active_donors_number }}</b>. Всего источников {{ object.donors.count }}
        </p>
        <p>Готово постов для предпостинга (не старше 8 часов): {{ object.get_ready_records.count }}</p>
        <p>
            Последний обычный пост от источника: "{{ object.get_last_common_record.donor }}" - это значит, что пост из этого источника
            будет игнорироваться при следующем постинге. Можно отключить эту настройку.
        </p>

        <h3>Статистика доноров за последние 24 часа</h3>
        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Донор</th>
                    <th scope="col">Готовых постов (не старше 8 часов)</th>
                    <th scope="col">Готовых постов (все)</th>
                    <th scope="col">Всего собрано</th>
                    <th scope="col">Всего запостили</th>
                    <th scope="col">Всего новых постов</th>
                    <th scope="col">Всего отфильтровано</th>
                    <th scope="col">Всего забраковано</th>
                </tr>
                </thead>
                <tbody>
                {% for donor in object.donors.all %}
                    <tr>
                        <th scope="row">
                            {% if donor.is_involved %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-check-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M10.97 4.97a.235.235 0 0 0-.02.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-1.071-1.05z"/>
                                </svg>
                            {% else %}
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                     class="bi bi-x-circle" viewBox="0 0 16 16">
                                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                    <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                                </svg>
                            {% endif %}
                            <a href="{{ donor.url }}">{{ donor.id }} {{ donor.name }}</a>
                        </th>
                        <td> {{ donor.get_ready_records | count_by_time:"8" }}</td>
                        <td> {{ donor.get_ready_records | count_by_time:"24" }}</td>
                        <td> {{ donor.records.all | count_by_time:"24" }}</td>
                        <td> {{ donor.get_posted_records | count_by_time:"24" }}</td>
                        <td> {{ donor.get_new_posts | count_by_time:"24" }}</td>
                        <td> {{ donor.get_filtered_records | count_by_time:"24" }}</td>
                        <td> {{ donor.get_failed_records | count_by_time:"24" }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>

        <h3>Статистика фильтров страпинга за последние 24 часа</h3>
        <p>Собрано постов: {{ object.get_all_records_last_day.count }}</p>

        <div class="table-responsive">
            <table class="table table-striped">
                <thead>
                <tr>
                    <th scope="col">Название фильтра</th>
                    <th scope="col">Количество отфильтрованых постов</th>
                </tr>
                </thead>
                <tbody>
                {% for name, data in object.filter_stats_last_day %}
                    <tr>
                        <th scope="row">{{ name }}</th>
                        <td>{{ data }} ({% widthratio data object.get_all_records_last_day.count 100 %}%)</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

vk_project/posting/templates/posting/index.html
{% extends 'posting/base.html' %}


{% block content %}
    <div class="container-lg">
        <h2>Все сообщества</h2>
    </div>
    <div class="container-lg">
        <div>
            {% if groups %}
                <ul class="list-group">
                    {% for group in groups %}
                        <li class="list-group-item">
                            <div class="row justify-content-md-center">
                                <div class="col-sm">
                                    <a href="{{ group.url }}">{{ group.name }}</a>
                                    <a href="{% url 'posting:groups' group.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                                            <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                                            <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                                        </svg>

                                    </a>

                                    <a href="{% url 'admin:posting_group_change' group.pk %}">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16"
                                             fill="currentColor"
                                             class="bi bi-pen" viewBox="0 0 16 16">
                                            <path d="m13.498.795.149-.149a1.207 1.207 0 1 1 1.707 1.708l-.149.148a1.5 1.5 0 0 1-.059 2.059L4.854 14.854a.5.5 0 0 1-.233.131l-4 1a.5.5 0 0 1-.606-.606l1-4a.5.5 0 0 1 .131-.232l9.642-9.642a.5.5 0 0 0-.642.056L6.854 4.854a.5.5 0 1 1-.708-.708L9.44.854A1.5 1.5 0 0 1 11.5.796a1.5 1.5 0 0 1 1.998-.001zm-.644.766a.5.5 0 0 0-.707 0L1.95 11.756l-.764 3.057 3.057-.764L14.44 3.854a.5.5 0 0 0 0-.708l-1.585-1.585z"></path>
                                        </svg>
                                    </a>

                                </div>

                                <div class="col-sm">
                                    {% if not group.is_post_time_in_interval %}
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-exclamation-triangle" viewBox="0 0 16 16">
                                            <path d="M7.938 2.016A.13.13 0 0 1 8.002 2a.13.13 0 0 1 .063.016.146.146 0 0 1 .054.057l6.857 11.667c.036.06.035.124.002.183a.163.163 0 0 1-.054.06.116.116 0 0 1-.066.017H1.146a.115.115 0 0 1-.066-.017.163.163 0 0 1-.054-.06.176.176 0 0 1 .002-.183L7.884 2.073a.147.147 0 0 1 .054-.057zm1.044-.45a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566z"/>
                                            <path d="M7.002 12a1 1 0 1 1 2 0 1 1 0 0 1-2 0zM7.1 5.995a.905.905 0 1 1 1.8 0l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995z"/>
                                        </svg>
                                    {% endif %}

                                    {% if group.get_last_record_time %}
                                        <span>Последний пост: {{ group.get_last_record_time | timesince }} назад </span>
                                    {% else %}
                                        <span>Нет постов</span>
                                    {% endif %}
                                </div>

                                <div class="col-sm">
                                    <span class="badge badge-primary badge-pill float-sm-right"> Источники: {{ group.get_active_donors_number }}/{{ group.donors.count }} </span>
                                </div>
                            </div>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p>No groups</p>
            {% endif %}
        </div>
    </div>
{% endblock %}

vk_project/posting/templates/posting/user.html
{% extends 'posting/base.html' %}
{% load bootstrap4 %}

{% block content %}

<div class="container-lg">
    <div>
        <h2>{{ user.login }}</h2>
        <a href="{% url 'admin:posting_user_change' user.pk %}">Go to admin</a>
    </div>

    <div>
        <form id="send_code">
            {% csrf_token %}
            {{ form }}
            <input name="code" id="code">
            <input type="hidden" name="user_pk" value="{{ user.pk }}">
            <input type="submit" class="btn btn-primary" value="Send Code" />
        </form>
        <form id="activate_2f">
            {% csrf_token %}
            {{ form }}
            <input type="hidden" name="user_pk" value="{{ user.pk }}">
            <input type="submit" class="btn btn-primary" value="Test two-factor" />
        </form>
        <p id="test_message"></p>

    </div>
</div>

    <script>
        $("#activate_2f").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            let serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'posting:activate' user.pk %}",
                data: serializedData,
                success: function (response) {
                    console.log(response)
                    {#let resp_json = $.parseJSON(response)#}
                    $("#test_message").html(JSON.stringify(response));
                },
                error: function (response) {
                    console.log(response)
                    $("#test_message").html('Error on server, see console');
                }
            })
        });
        $("#send_code").submit(function (e) {
            // preventing from page reload and default actions
            e.preventDefault();
            // serialize the data for sending the form data.
            let serializedData = $(this).serialize();
            // make POST ajax call
            $.ajax({
                type: 'POST',
                url: "{% url 'posting:user' user.pk %}",
                data: serializedData,
                success: function (response) {
                    console.log(response)
                    $("#send_code")[0].reset()
                },
                error: function (response) {
                    console.log(response)
                }
            })
        })
    </script>

{% endblock %}

vk_project/posting/templates/posting/users.html
{% extends 'posting/base.html' %}

{% block content %}

<div class="container-lg">
    <ul>
        {% for user in users %}
        <li><a href="{% url 'posting:user' user.pk %}">{{ user.login }}</a></li>
        {% endfor %}
    </ul>
</div>

{% endblock %}